x-airflow-common-env: &airflow-common-env
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
  AIRFLOW__WEBSERVER__SECRET_KEY: dataflow_shared_secret_key_12345

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dataflow
      POSTGRES_PASSWORD: dataflow
      POSTGRES_DB: dataflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.10.2
    depends_on:
      - airflow-postgres
    environment:
      <<: *airflow-common-env
    volumes:
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    entrypoint: /bin/bash
    command: -c "airflow db migrate && airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com"

  airflow-webserver:
    build: .
    depends_on:
      - airflow-init
    environment:
      <<: *airflow-common-env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./dbt_project:/opt/airflow/dbt_project
      - ./.dbt/profiles.yml:/home/airflow/.dbt/profiles.yml:ro
      - ./gx:/opt/airflow/gx
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build: .
    depends_on:
      - airflow-init
    environment:
      <<: *airflow-common-env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./dbt_project:/opt/airflow/dbt_project
      - ./.dbt/profiles.yml:/home/airflow/.dbt/profiles.yml:ro
      - ./gx:/opt/airflow/gx
    command: scheduler

volumes:
  pgdata:
  airflow_pgdata:
