dataflow:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: dataflow
      password: dataflow
      port: 5432
      dbname: dataflow
      schema: public
      threads: 4